import prisma from "./lib/prisma.ts";

await prisma.posyandu.createMany({
  data: [
    {
      id: 1,
      kodePosyandu: "POS001",
      namaPosyandu: "Posyandu Melati 1",
      kecamatan: "Gresik",
      puskesmas: "Puskesmas Gresik 1",
      desaKelurahan: "Gresik Kota",
      alamat: "Jl. Ahmad Yani No. 10, Gresik",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 2,
      kodePosyandu: "POS002",
      namaPosyandu: "Posyandu Mawar 1",
      kecamatan: "Gresik",
      puskesmas: "Puskesmas Gresik 1",
      desaKelurahan: "Karangpoh",
      alamat: "Jl. Sunan Giri No. 25, Gresik",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 3,
      kodePosyandu: "POS003",
      namaPosyandu: "Posyandu Dahlia 2",
      kecamatan: "Gresik",
      puskesmas: "Puskesmas Gresik 2",
      desaKelurahan: "Sidokumpul",
      alamat: "Jl. Veteran No. 15, Gresik",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 4,
      kodePosyandu: "POS004",
      namaPosyandu: "Posyandu Anggrek 2",
      kecamatan: "Gresik",
      puskesmas: "Puskesmas Gresik 2",
      desaKelurahan: "Tlogopojok",
      alamat: "Jl. Dr. Wahidin No. 8, Gresik",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 5,
      kodePosyandu: "POS005",
      namaPosyandu: "Posyandu Tulip 1",
      kecamatan: "Kebomas",
      puskesmas: "Puskesmas Kebomas 1",
      desaKelurahan: "Kebomas",
      alamat: "Jl. Raya Kebomas No. 20, Kebomas",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 6,
      kodePosyandu: "POS006",
      namaPosyandu: "Posyandu Kenanga 1",
      kecamatan: "Kebomas",
      puskesmas: "Puskesmas Kebomas 1",
      desaKelurahan: "Randuagung",
      alamat: "Jl. Randuagung Raya No. 12, Kebomas",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 7,
      kodePosyandu: "POS007",
      namaPosyandu: "Posyandu Cempaka 2",
      kecamatan: "Kebomas",
      puskesmas: "Puskesmas Kebomas 2",
      desaKelurahan: "Kembangan",
      alamat: "Jl. Kembangan Indah No. 30, Kebomas",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
    {
      id: 8,
      kodePosyandu: "POS008",
      namaPosyandu: "Posyandu Seroja 2",
      kecamatan: "Kebomas",
      puskesmas: "Puskesmas Kebomas 2",
      desaKelurahan: "Bungah",
      alamat: "Jl. Bungah Permai No. 18, Kebomas",
      password: "$2y$10$LewuSRSQ8vkNIQEpOJ3wh.df7TAKOH1c6WFq1FX8fARPE38H/nfwi",
    },
  ],
  skipDuplicates: true, // opsional: biar tidak error kalau ID sudah ada
});
